# Generated by Django 4.0.2 on 2022-08-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('hscPercent', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('pathways', models.ManyToManyField(to='interactions.Pathway')),
            ],
        ),
        migrations.CreateModel(
            name='Ligand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('pathways', models.ManyToManyField(to='interactions.Pathway')),
            ],
        ),
        migrations.CreateModel(
            name='cellClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('receivingPathways', models.ManyToManyField(related_name='receivingPathways', to='interactions.Pathway')),
                ('sendingPathways', models.ManyToManyField(related_name='sendingPathways', to='interactions.Pathway')),
            ],
        ),
    ]
