# Generated by Django 4.0.2 on 2022-08-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cellclass',
            name='receivingPathways',
        ),
        migrations.RemoveField(
            model_name='cellclass',
            name='sendingPathways',
        ),
        migrations.AddField(
            model_name='pathway',
            name='receivingCellTypes',
            field=models.ManyToManyField(related_name='receivingPathways', to='interactions.cellClass'),
        ),
        migrations.AddField(
            model_name='pathway',
            name='sendingCellTypes',
            field=models.ManyToManyField(related_name='sendingPathways', to='interactions.cellClass'),
        ),
    ]
