# Generated by Django 4.0.2 on 2022-08-17 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_remove_cellclass_receivingpathways_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathway',
            name='receivingCellTypes',
        ),
        migrations.RemoveField(
            model_name='pathway',
            name='sendingCellTypes',
        ),
        migrations.AddField(
            model_name='cellclass',
            name='receivingPathways',
            field=models.ManyToManyField(related_name='receivingPathways', to='interactions.Pathway'),
        ),
        migrations.AddField(
            model_name='cellclass',
            name='sendingPathways',
            field=models.ManyToManyField(related_name='sendingPathways', to='interactions.Pathway'),
        ),
        migrations.CreateModel(
            name='pathway_celltype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hscPercent', models.FloatField()),
                ('celltype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interactions.cellclass')),
                ('pathway', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interactions.pathway')),
            ],
        ),
    ]
