# Generated by Django 4.0.2 on 2022-08-17 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_remove_pathway_receivingcelltypes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pathway_celltype',
            new_name='pathwayAndCelltype',
        ),
    ]
