# Generated by Django 4.0.2 on 2022-08-17 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_rename_pathway_celltype_pathwayandcelltype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cellClass',
            new_name='cellClas',
        ),
    ]
