# Generated by Django 4.0.2 on 2022-08-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0006_pathwayandcelltype_sorr'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathway',
            name='interaction_type',
            field=models.CharField(choices=[('c', 'Cell-Cell Contact'), ('e', 'ECM-Receptor'), ('s', 'Secreted Signaling')], default='s', max_length=1),
        ),
    ]
