# Generated by Django 4.0.2 on 2022-08-19 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0010_alter_pathwayandcelltype_averagescore_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pathway',
            options={'ordering': ['interaction_type', 'name']},
        ),
    ]
