# Generated by Django 4.0.2 on 2022-08-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0011_alter_pathway_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cellclas',
            options={'ordering': ['cell_type', 'name']},
        ),
        migrations.AddField(
            model_name='pathway',
            name='ligands',
            field=models.ManyToManyField(related_name='pathway_ligand', to='interactions.Ligand'),
        ),
        migrations.AddField(
            model_name='pathway',
            name='receptors',
            field=models.ManyToManyField(related_name='pathway_receptor', to='interactions.Receptor'),
        ),
    ]
