# Generated by Django 3.2.15 on 2022-08-19 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0012_alter_cellclas_options_pathway_ligands_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pathwayandcelltype',
            options={'ordering': ['sorr', 'pathway', 'celltype', '-hscPercent', '-averageScore']},
        ),
    ]
