# Generated by Django 3.2.15 on 2022-08-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0013_alter_pathwayandcelltype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligand',
            name='receptors',
            field=models.ManyToManyField(to='interactions.Receptor'),
        ),
        migrations.AddField(
            model_name='receptor',
            name='ligands',
            field=models.ManyToManyField(to='interactions.Ligand'),
        ),
    ]
