# Generated by Django 3.2.15 on 2022-09-13 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0014_auto_20220822_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ligand',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='receptor',
            options={'ordering': ['name']},
        ),
    ]
