# Generated by Django 3.2.15 on 2023-10-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0019_auto_20221206_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathway',
            name='hscPercent',
        ),
        migrations.AddField(
            model_name='pathwayandcelltype',
            name='hspc_type',
            field=models.CharField(default='HSC', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pathwaycorrelations',
            name='hspc_type',
            field=models.CharField(default='HSC', max_length=5),
            preserve_default=False,
        ),
    ]
