# Generated by Django 3.2.15 on 2024-10-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0020_auto_20231009_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathwayandcelltype',
            name='sorr',
            field=models.CharField(choices=[('s', 'Source'), ('t', 'Target')], default='s', max_length=1),
        ),
        migrations.AlterField(
            model_name='pathwaycorrelations',
            name='p1a',
            field=models.CharField(choices=[('s', 'Source'), ('t', 'Target')], default='s', max_length=1),
        ),
        migrations.AlterField(
            model_name='pathwaycorrelations',
            name='p2a',
            field=models.CharField(choices=[('s', 'Source'), ('t', 'Target')], default='s', max_length=1),
        ),
    ]
