# Generated by Django 3.2.15 on 2025-03-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0021_auto_20241014_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pathwayandcelltype',
            options={'ordering': ['sorr', 'pathway', 'celltype', '-hscPercent', '-averageScore', '-specificityIndex']},
        ),
        migrations.AddField(
            model_name='pathwayandcelltype',
            name='specificityIndex',
            field=models.FloatField(default=None),
        ),
    ]
