# Generated by Django 3.2.15 on 2025-03-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0022_auto_20250320_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathwayandcelltype',
            name='specificityIndex',
            field=models.FloatField(default=-1),
        ),
    ]
