# Generated by Django 3.2.15 on 2025-03-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0024_alter_pathwayandcelltype_specificityindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathwayandcelltype',
            name='specificityIndex',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
