# Generated by Django 3.2.15 on 2025-11-10 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0027_alter_pathwayandcelltype_specificityindex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pathwayandcelltype',
            options={'ordering': ['sorr', 'pathway', 'celltype', '-hscPercent', '-averageScore']},
        ),
        migrations.RemoveField(
            model_name='pathwayandcelltype',
            name='specificityIndex',
        ),
    ]
