# Generated by Django 3.2.15 on 2025-11-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0028_auto_20251110_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathwaycorrelations',
            name='correlation',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pathwaycorrelations',
            name='pval',
            field=models.FloatField(default=0, null=True),
        ),
    ]
