# Generated by Django 3.2.15 on 2025-11-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0029_auto_20251110_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathwayandcelltype',
            name='specificity_index',
            field=models.FloatField(default=0),
        ),
    ]
