# Generated by Django 3.2.15 on 2025-11-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0030_pathwayandcelltype_specificity_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathway',
            name='specificity_index_r',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pathway',
            name='specificity_index_s',
            field=models.FloatField(default=0),
        ),
    ]
